#!/bin/sh

if pidof picom;
then
	killall picom;
	notify-send -a Picom -i /usr/share/icons/Dracula/symbolic/devices/laptop-symbolic.svg -u normal -t 3000 "Picom killed"	
	#dunstify -u normal -r 609 -t 3000 "Picom killed"
else
	picom --backend glx --xrender-sync-fence &
	notify-send -a Picom -i /usr/share/icons/Dracula/symbolic/devices/laptop-symbolic.svg -u normal -t 3000 "Picom Started"
	#dunstify -u normal -r 609 -t 3000 "Picom Started"
fi
